name: 'actions-toolkit-py'
description: 'Run a python script with some baked-in utility functions'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  script:
    description: 'Python script to run'
    required: true
    default: ''
  event:
    description: 'The GitHub Event Object'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - |
      cat <<EOF >> /work/script.py
      ${{ inputs.script }}
      EOF
      
      /work/script.py
      
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
