---
name: Test the GitHub action in this Repository
on: [push]

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: Test the GitHub action in this Repository
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test this Action
        id: test-action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          event: |
            ${{ github.event }}
          script: |
            print("hello, world")
            three = 1 + 2
            print(three)


            import json
            import os
            with os.open('/work/event.json') as f:
              obj = json.load(f)
            print(json.dumps(obj))
